name : 04 - Using Actions

on : push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v4
        - name: Printing Folders
          run: ls

    # 0. checkout the code from the repository
    # 1. Install deps of our react application
    # 2. Execute automated tests