/*
Tasks:

1. Add the following triggers to your workflow: push, workflow_dispatch

2. Add a single job to the workflow named echo-data that runs on ubuntu-latest with two steps:
   a. First step named "Display Information" - print the following lines from the github context using multi-line script with echo commands:
      - "Event name: <retrieve the event name here>"
      - "Ref: <retrieve the ref here>"
      - "SHA: <retrieve the commit sha here>"
      - "Actor: <retrieve the actor name here>"
      - "Workflow: <retrieve the workflow name here>"
      - "Run ID: <retrieve the run ID here>"
      - "Run number: <retrieve the run number here>"
   b. Second step named "Retrieve Variable" - print a single line containing the value of repository variable MY_VAR

3. Create a repository variable named MY_VAR with the value "hello world"

4. Commit the changes and push the code. Inspect the output of the workflow run.

5. Add a top-level run-name configuration key set to "My custom workflow run name - ${{ runner.os }}"
   - Commit and push. Which error message appeared?

6. Replace the run-name with "06 - Contexts | DEBUG - ${{ inputs.debug }}"

7. Add an input to the workflow_dispatch trigger named debug with boolean type and default value false

8. Commit and push. Trigger the workflow from the UI with different values for the debug input. How does this impact the results?

9. Add a top-level env key with two environment variables:
   - MY_WORKFLOW_VAR: 'workflow'
   - MY_OVERWRITTEN_VAR: 'workflow'

10. Under the echo-data job, add an env key with two environment variables:
    - MY_JOB_VAR: 'job'
    - MY_OVERWRITTEN_VAR: 'job'

11. Add a step after "Retrieve Variable" named "Print Env Variables" with env key:
    - MY_OVERWRITTEN_VAR: 'step'
    - Execute multi-line script to print:
      - "Workflow env: <retrieve MY_WORKFLOW_VAR here>"
      - "Overwritten env: <retrieve MY_OVERWRITTEN_VAR here>"

12. Add another step after the first "Print Env Variables" (without additional env variables)
    - Execute multi-line script to print:
      - "Workflow env: <retrieve MY_WORKFLOW_VAR here>"
      - "Overwritten env: <retrieve MY_OVERWRITTEN_VAR here>"
*/



name: 06 - Contexts

on: push

jobs:
    echo-data:
        runs-on: ubuntu-latest
        steps:
            - name: Display information
              run: |
                echo "Event Name: ${{github.event_name}}"
                echo "Ref: ${{github.ref}}"
                echo "SHA: ${{github.sha}}"
                echo "Actor: ${{github.actor}}"
                echo "Workflow: ${{github.workflow}}"
                echo "Run ID: ${{github.run_id}}"
                echo "Run number: ${{github.run_number}}"

            - name: Retrieve variable
              run: |
                echo "Variable value: ${{ vars.MY_VAR }}"  
                