name: 08 - Using variables

on:
  push:
  workflow_dispatch:

env:
  WORKFLOW_VAR: 'I am a workflow env var'
  OVERWRITTEN: 'I will be be overwritten'

jobs:
  echo:
    runs-on: ubuntu-latest
    env:
      JOB_VAR: 'I am a job env var'
      OVERWRITTEN: 'I am a job env var that overwriten at job level'
    steps:
      - name: Print Environment Variable
        env:
          STEP_VAR: "I am a step env var"
          step_var2: "I am another step env var"
        run: |
          echo "Step env var: ${{ env.STEP_VAR }}"
          echo "Step var2: ${{ env.step_var2 }}"
          echo "Job env var: ${{ env.JOB_VAR }}"
          echo "Overwritten: ${{ env.OVERWRITTEN }}"
      - name: Overwrite job variable
        env: 
          OVERWRITTEN: "I am a step env var that overwriten at step level"
          run: |
          echo "Overwritten: ${{ env.OVERWRITTEN }}"
